apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iyad-devops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps
    repoURL: https://github.com/iyad87/argocd-demo-apps
    targetRevision: HEAD 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true 


