apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sonarqube
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/sonarqube
    repoURL: https://github.com/SonarSource/helm-chart-sonarqube
    targetRevision: HEAD
    helm:
       values: | 
          ingress:
          enabled: false
          hosts:
            - name: sonarqube.{{ .Values.cluster }}.{{ .Values.project }}.{{ .Values.domain }}
              path: /
          annotations:
            kubernetes.io/tls-acme: "true"
            cert-manager.io/cluster-issuer: letsencrypt-prod
          tls:
            - secretName: {{ include "common-argo.fullname" . }}-sonarqube-tls
              hosts:
                - sonarqube.{{ .Values.cluster }}.{{ .Values.project }}.{{ .Values.domain }}
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true 


