apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sonarqube
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/sonarqube
    repoURL: https://github.com/SonarSource/helm-chart-sonarqube
    targetRevision: HEAD
    helm:
       values: | 
          ingress:
          enabled: false
          
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true 


